# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa0e4f83ba51b4cabbd211a1b9303905a4ba58fb687474dda02c35f23a94d05267edda43d6bb7cd472bccb8e103bacfedefe9180ffad36123dc1a75d22bee607

test:
  secret_key_base: a27676dc8a9905d9e03a332d792088a67ab27efd8e3a851096c263511acff3b56896bfec15ba9ba4c7e68da8e00ee3fe5a6b9e110814ff926ed49c11ff534f2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
